# Generated by Django 4.1.5 on 2023-01-11 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
