# Generated by Django 4.1.5 on 2023-01-11 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0003_rename_tag_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
